# Generated by Django 6.1.1 on 2026-09-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminTaller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='criticidad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], default='Baja', max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50),
        ),
    ]
