# Generated by Django 6.1.1 on 2026-09-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminTaller', '0003_empleado_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='password_change_required',
            field=models.BooleanField(default=True),
        ),
    ]
